# Form implementation generated from reading ui file 'C:\Users\Hoàng Sang\Documents\TMĐT HK4\1.Kĩ thuật lập trình\Pycharm-KTLT\Exercise_KTLT\Ex24\ui\MainWindow24.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(506, 356)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 20, 421, 281))
        self.groupBox.setObjectName("groupBox")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(40, 130, 101, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(40, 170, 91, 31))
        self.label_5.setObjectName("label_5")
        self.labelMachine = QtWidgets.QLabel(parent=self.groupBox)
        self.labelMachine.setGeometry(QtCore.QRect(140, 130, 141, 31))
        self.labelMachine.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"color: rgb(0, 0, 0);")
        self.labelMachine.setObjectName("labelMachine")
        self.labelPlayer = QtWidgets.QLabel(parent=self.groupBox)
        self.labelPlayer.setGeometry(QtCore.QRect(140, 170, 141, 31))
        self.labelPlayer.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"color: rgb(0, 0, 0);")
        self.labelPlayer.setObjectName("labelPlayer")
        self.pushButtonRandom = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonRandom.setGeometry(QtCore.QRect(40, 230, 91, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\Hoàng Sang\\Documents\\TMĐT HK4\\1.Kĩ thuật lập trình\\Pycharm-KTLT\\Exercise_KTLT\\Ex24\\ui\\../images/ic_random.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonRandom.setIcon(icon)
        self.pushButtonRandom.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonRandom.setObjectName("pushButtonRandom")
        self.pushButtonNewGame = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonNewGame.setGeometry(QtCore.QRect(160, 230, 91, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\Hoàng Sang\\Documents\\TMĐT HK4\\1.Kĩ thuật lập trình\\Pycharm-KTLT\\Exercise_KTLT\\Ex24\\ui\\../images/ic_newgame.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonNewGame.setIcon(icon1)
        self.pushButtonNewGame.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonNewGame.setObjectName("pushButtonNewGame")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonExit.setGeometry(QtCore.QRect(280, 230, 91, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\Hoàng Sang\\Documents\\TMĐT HK4\\1.Kĩ thuật lập trình\\Pycharm-KTLT\\Exercise_KTLT\\Ex24\\ui\\../images/ic_exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonExit.setIcon(icon2)
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.label_1 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_1.setGeometry(QtCore.QRect(100, 40, 51, 61))
        self.label_1.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(170, 255, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label_1.setText("")
        self.label_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(180, 40, 51, 61))
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(170, 255, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(260, 40, 51, 61))
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(170, 255, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 506, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Lucky Game:"))
        self.label_4.setText(_translate("MainWindow", "machine money:"))
        self.label_5.setText(_translate("MainWindow", "player money:"))
        self.labelMachine.setText(_translate("MainWindow", "100"))
        self.labelPlayer.setText(_translate("MainWindow", "100"))
        self.pushButtonRandom.setText(_translate("MainWindow", "Random"))
        self.pushButtonNewGame.setText(_translate("MainWindow", "New Game"))
        self.pushButtonExit.setText(_translate("MainWindow", "Exit"))
