# Form implementation generated from reading ui file 'C:\Users\Hoàng Sang\Documents\TMĐT HK4\1.Kĩ thuật lập trình\Pycharm-KTLT\Exercise_KTLT\Ex117\ui\MainWindow117.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(412, 416)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEditData = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditData.setGeometry(QtCore.QRect(30, 50, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditData.setFont(font)
        self.lineEditData.setObjectName("lineEditData")
        self.pushButtonCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonCalculate.setGeometry(QtCore.QRect(160, 100, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonCalculate.setFont(font)
        self.pushButtonCalculate.setObjectName("pushButtonCalculate")
        self.labelResult = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelResult.setGeometry(QtCore.QRect(30, 150, 351, 211))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelResult.setFont(font)
        self.labelResult.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"color: rgb(255, 170, 0);")
        self.labelResult.setText("")
        self.labelResult.setObjectName("labelResult")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 412, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Enter data: comma-seperated:"))
        self.lineEditData.setText(_translate("MainWindow", "2,3,4,6,62,7,4,7,1"))
        self.pushButtonCalculate.setText(_translate("MainWindow", "Calculate"))
