# Form implementation generated from reading ui file 'C:\Users\Hoàng Sang\Documents\TMĐT HK4\1.Kĩ thuật lập trình\Pycharm-KTLT\Exercise_KTLT\Ex22\ui\MainWindow22.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(605, 522)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 70, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 120, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 190, 121, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 300, 111, 21))
        self.label_4.setObjectName("label_4")
        self.lineEditTotalBulb = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditTotalBulb.setGeometry(QtCore.QRect(180, 70, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditTotalBulb.setFont(font)
        self.lineEditTotalBulb.setObjectName("lineEditTotalBulb")
        self.lineEditDamaged = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditDamaged.setGeometry(QtCore.QRect(180, 130, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditDamaged.setFont(font)
        self.lineEditDamaged.setObjectName("lineEditDamaged")
        self.lineEditPicked = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditPicked.setGeometry(QtCore.QRect(180, 190, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditPicked.setFont(font)
        self.lineEditPicked.setObjectName("lineEditPicked")
        self.lineEditProbability = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditProbability.setGeometry(QtCore.QRect(180, 300, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditProbability.setFont(font)
        self.lineEditProbability.setObjectName("lineEditProbability")
        self.pushButtonCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonCalculate.setGeometry(QtCore.QRect(230, 240, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonCalculate.setFont(font)
        self.pushButtonCalculate.setObjectName("pushButtonCalculate")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 605, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Total light bulbs:"))
        self.label_2.setText(_translate("MainWindow", "Damaged bulbs:"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Picked bulbs:</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Probability:</span></p></body></html>"))
        self.pushButtonCalculate.setText(_translate("MainWindow", "Calculate"))
